
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin/"
      - "/opt/homebrew/opt/openjdk@17/bin/"
      - "/Users/mickymacm4/Library/Android/sdk/platform-tools/"
      - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin/"
      - "/Users/mickymacm4/Library/Android/sdk/tools/"
      - "/Users/mickymacm4/Library/Android/sdk/tools/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/mickymacm4/.dotnet/tools/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
    searched_directories:
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin/uname"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/uname"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten/uname"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin/uname"
      - "/opt/homebrew/opt/openjdk@17/bin/uname"
      - "/Users/mickymacm4/Library/Android/sdk/platform-tools/uname"
      - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin/uname"
      - "/Users/mickymacm4/Library/Android/sdk/tools/uname"
      - "/Users/mickymacm4/Library/Android/sdk/tools/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin"
        - "/Users/mickymacm4/Documents/emscripten/emsdk"
        - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten"
        - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin"
        - "/opt/homebrew/opt/openjdk@17/bin"
        - "/Users/mickymacm4/Library/Android/sdk/platform-tools"
        - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin"
        - "/Users/mickymacm4/Library/Android/sdk/tools"
        - "/Users/mickymacm4/Library/Android/sdk/tools/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
        - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten/"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin/"
      - "/opt/homebrew/opt/openjdk@17/bin/"
      - "/Users/mickymacm4/Library/Android/sdk/platform-tools/"
      - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin/"
      - "/Users/mickymacm4/Library/Android/sdk/tools/"
      - "/Users/mickymacm4/Library/Android/sdk/tools/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/mickymacm4/.dotnet/tools/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
    searched_directories:
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/install_name_tool"
      - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/install_name_tool"
      - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin/install_name_tool"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/install_name_tool"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten/install_name_tool"
      - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin/install_name_tool"
      - "/opt/homebrew/opt/openjdk@17/bin/install_name_tool"
      - "/Users/mickymacm4/Library/Android/sdk/platform-tools/install_name_tool"
      - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin/install_name_tool"
      - "/Users/mickymacm4/Library/Android/sdk/tools/install_name_tool"
      - "/Users/mickymacm4/Library/Android/sdk/tools/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin"
        - "/Users/mickymacm4/Documents/emscripten/emsdk"
        - "/Users/mickymacm4/Documents/emscripten/emsdk/upstream/emscripten"
        - "/Users/mickymacm4/Documents/emscripten/emsdk/node/24.19.0_64bit/bin"
        - "/opt/homebrew/opt/openjdk@17/bin"
        - "/Users/mickymacm4/Library/Android/sdk/platform-tools"
        - "/Users/mickymacm4/Library/Android/sdk/cmdline-tools/latest/bin"
        - "/Users/mickymacm4/Library/Android/sdk/tools"
        - "/Users/mickymacm4/Library/Android/sdk/tools/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
        - "/Users/mickymacm4/.vscode/extensions/vadimcn.vscode-lldb-1.12.3/bin"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/mickymacm4/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
